feriavirtual2/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feriavirtualapp.urls')),
]

feriavirtualapp/urls.py
from django.urls import path , include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from .views import *
urlpatterns = [
    path('lista-contratos/', views.listaContratos, name='listaContratos'),
    path('gestion-contratos/', views.gestionContratos, name='gestionContratos'),
    path('contratos/', views.contratos, name='contratos'),
    path('register/', views.register, name='register'),
    path('registerinterno/', views.registerinterno, name='register-interno'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('', views.index, name='index'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    
    path('pagar/<int:total>/<int:pk>', views.pagar, name="pagar"),
 
    path('seguimiento/<int:pk>/', views.seguimiento, name="seguimiento"),
    path('seguimientoLista/', views.seguimientoLista, name='seguimientoLista'),
    path('seguimientoDetalle/<int:pk>/', views.seguimientoDetalle, name='seguimientoDetalle'),

    
    
    path('ingresar-productos/', views.ingresarproductos, name='ingresar-productos'),
    path('mis-productos/', views.misproductos, name='mis-productos'),
    
    
    path('venta/', views.venta, name='venta'),
    
    # path('subasta/<int:pk>/', views.subasta, name='subasta'),
    path('subasta/', views.subasta, name='subasta'),
    #path('pagarsubasta/<int:pk>/', views.pagarsubasta, name='pagarsubasta'),
    path('terminar/<int:pk>/', views.terminar, name='terminar'),
    path('terminarsaldo/', views.webpaycommit, name='terminarsaldo'),
    #path('pagar/<int:total>/<int:pk>', views.pagar, name='pagar'),
    path('pagar/', views.pagar, name='pagar'),
    
    path('Solicitud/', views.Solicitud, name='Solicitud'),
    path('Solicitudes/', views.solicitudes, name='Solicitudes'),
    path('modificarsoli/<int:pk>/', views.modificarSolicitud, name="modificarSolicitud"),

    path('registrarTransporte/', views.registrarTransporte, name="registrarTransporte"),
    path('transportesRegistrados/', views.transportesRegistrados, name="transportesRegistrados"),

    path('Venta-local/', views.Ventalocal, name="Ventalocal"),
    
    
    path('add_product_carrito/<int:product_id>/', add_product_carrito, name='add_product_carrito'),
    path('add_product_catalogo/<int:product_id>/', add_product_catalogo, name='add_product_catalogo'),
    path('remove_product/<int:product_id>/', remove_product, name='remove_product'),
    path('decrement_product/<int:product_id>/', decrement_product, name='decrement_product'),
    path('clear/', clear_cart, name='clear_cart'),
    path('carrito.html', views.webpay),

    path('solicitudClientes/', views.solicitudClientes, name="solicitudClientes"),

    path('solicitudesTransportista/', views.solicitudesTransportista, name="solicitudesTransportista"),
    path('modificarSolicitudTransportista/<int:pk>/', views.modificarSolicitudTransportista, name="modificarSolicitudTransportista"),

    path('solicitudesRevisor/', views.solicitudesRevisor, name="solicitudesRevisor"),
    path('modificarSolicitudRevisor/<int:pk>/', views.modificarSolicitudRevisor, name="modificarSolicitudRevisor"),

    path('solicitudesProductor/', views.solicitudesProductor, name="solicitudesProductor"),
    path('modificarsolicitudProductor/<int:pk>/', views.modificarSolicitudProductor, name="modificarsolicitudProductor"),

    path('solicitudesClienteExterno/', views.solicitudesClienteExterno, name="solicitudesClienteExterno"),
    path('modificarSolicitudClienteExterno/<int:pk>/', views.modificarSolicitudClienteExterno, name="modificarSolicitudClienteExterno"),
    path('modificar/<int:id>', views.modProducto1, name = 'modificar'),
    path('eliminar/<int:id>', views.elimProducto, name = 'eliminar'),
    path('modificarTransporte/<int:id>', views.modTransporte, name = 'modificarTransporte'),
    path('', include('pwa.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feriavirtualapp/models.py
from email.policy import default
from pickle import TRUE
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import fields
from django.db.models.fields import related
from django.utils import timezone
PRODUCTOS =(
    ("1", "Cerezas "),
    ("2", "Uvas"),
    ("3", "Arándanos "),
    ("4", "Nueces"),
    ("5", "Manzana"),
    ("6", "Ciruela"),
    ("7", "Peras"),
    ("9", "Durazno"),
    ("11", "Frutilla"),
    ("12", "Granada"),
    ("13", "Limón"),
    ("14", "Mandarina"),
    ("15", "Naranja"),
    ("16", "Sandia "),
    ("17", "Melón"),
    ("18", "Mora"),
    ("19", "Pera"),
    ("20", "Manzana"),
    )
#ATENDIENDO TAMAÑO Y CALIBRE LA FRUTA SE PUEDE CALIFICAR EN:
CALIBRE =(
    ("1", "Segunda"),
    ("2", "Primera"),
    ("3", "Extra "),
)
TAMAÑO =(
    ("1", "Ligero "),
    ("2", "Liviano"),
    ("3", "Semi Liviano"),
    ("4", "Mediano"),
    ("5", "Semi esado"),
    ("6", "Pesado"),
    ("7", "Extra Pesado"),
    ("8", "Mega Pesado"),
    ("9", "Ultra Pesado"),
    ("10", "Extra Pesado"),
    ("11", "Giga Pesado"),
    ("12", "Super Pesado"),
    )
EstadoSolicitudCompra =(
    ("1", "Aprobado"),
    ("2", "Rechazado"),
    ("3", "Pendiente"),
    ("4", "Subasta de transporte"),
    ("5", "Transporte Listo"),
    ("6","Entregado en bodega"),
    ("7","Viaje interrumpido (productor)"),
    ("8", "Revision de calidad"),
    ("9", "Rechazado en revision"),
    ("10", "Revisado"),
    ("11", "En camino"),
    ("12", "Viaje interrumpido (transportista)"),
    ("13", "Destino"),
    ("14", "Aceptado por el destinatario"),
    ("15", "Rechazado por el destinatario"),
    ("16", "Saldo"),
    ("17", "Completado")


    
    )
class User(AbstractUser):
    ROLES =(
    ("1", "Productor"),
    ("2", "Cliente externo"),
    ("3", "Cliente interno"),
    ("4", "Transportista"),
    ("5", "Consultor"),
    ("6", "Administrador"),
    ("7", "Revisor de calidad"),
    )
    dni = models.CharField(max_length=30,null=True)
    rol = models.CharField(max_length=50, choices = ROLES, null=True, default=3)
    imagen = models.ImageField(upload_to="Perfil",default='Perfil/default.png')
    direccion=models.CharField(max_length=50, null=True)
    codigopostal=models.IntegerField(default=0, null=True)
    def __str__(self):
        return f'{self.username}'
    



class Producto(models.Model):
    
    autor = models.ForeignKey(User, on_delete=models.CASCADE,related_name='producto')
    producto = models.CharField(max_length=50, choices = PRODUCTOS, null=True)
    variedad = models.CharField(max_length=50, null=True)
    calibre = models.CharField(max_length=50,choices = CALIBRE, null=True)
    cantidad = models.IntegerField(default=0)
    fecha_subida = models.DateTimeField(default=timezone.now)
    imagen = models.ImageField(upload_to="Productos", null=True)
    precio = models.IntegerField(default=0)
    Saldo= models.BooleanField(default=True)
    def __str__(self):
        return f'{self.autor.username}: {self.producto}: { self.variedad} :  { self.calibre} : { self.cantidad}: { self.fecha_subida}: { self.imagen}: { self.precio}'


class Contrato(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_inicio = models.DateField(default=timezone.now)
    fecha_termino = models.DateField(default=timezone.now)
    vigencia = models.BooleanField(default=False)

class Transporte(models.Model):
    transportista = models.ForeignKey(User, on_delete=models.CASCADE)
    tamaño = models.CharField(max_length=50, choices = TAMAÑO, null=True)
    refrigeracion = models.BooleanField(default=False)
    tarifa = models.IntegerField(default=0)
    disponible= models.BooleanField(default=True)
    def __str__(self):
        return f'{self.transportista.username}: tamaño: {self.tamaño}: Refrigeracion: {self.refrigeracion}: Tarifa: {self.tarifa} {self.disponible}: Disponibilidad'

    

class Post(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    producto = models.CharField(max_length=50, choices = PRODUCTOS, null=True)
    productor = models.ForeignKey(User, on_delete=models.CASCADE,related_name="productor" ,null=True)
    variedad = models.CharField(max_length=50, null=True)
    calibre = models.CharField(max_length=50, choices = CALIBRE, null=True,default=1)
    cantidad_actual = models.IntegerField(default=0)
    cantidad_necesaria = models.IntegerField(default=0)
    contenido = models.CharField(max_length=50, null=True)
    refrigeracion = models.BooleanField(default=False)
    cliente = models.ForeignKey(User, on_delete=models.CASCADE,related_name='ClienteSoli')
    fecha_creacion = models.DateTimeField(default=timezone.now)
    imagen = models.ImageField(upload_to="Posts", null=True)
    EstadoSolicitud = models.CharField(max_length=50, null=True, choices=EstadoSolicitudCompra, default='3')
    transportista = models.ForeignKey(User, on_delete=models.CASCADE, null=True,related_name="transportista")
    transporte = models.ForeignKey(Transporte, on_delete=models.CASCADE, null=True,related_name="transporte")
    comentariosTransportista = models.TextField(default="")
    class Meta:
        ordering = ['-fecha_creacion']
    def publish(self):
        self.fecha_publicacion = timezone.now()
        self.save()

class Posthistorico(models.Model):
    
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    idpost= models.ForeignKey(Post,on_delete=models.CASCADE,null=True)
    producto = models.CharField(max_length=50, choices = PRODUCTOS, null=True)
    productor = models.ForeignKey(User, on_delete=models.CASCADE,related_name="productorh" ,null=True)
    variedad = models.CharField(max_length=50, null=True)
    calibre = models.CharField(max_length=50, choices = CALIBRE, null=True,default=1)
    cantidad_actual = models.IntegerField(default=0,null=True)
    cantidad_necesaria = models.IntegerField(default=0,null=True)
    contenido = models.CharField(max_length=50, null=True)
    refrigeracion = models.BooleanField(default=False,null=True)
    cliente = models.ForeignKey(User, on_delete=models.CASCADE,related_name='ClienteSolih',null=True)
    fecha_creacion = models.DateTimeField(default=timezone.now,null=True)
    fecha_modificacion = models.DateTimeField(null=True)
    imagen = models.ImageField(upload_to="Posts", null=True)
    EstadoSolicitud = models.CharField(max_length=50, null=True, choices=EstadoSolicitudCompra, default='3')
    transportista = models.ForeignKey(User, on_delete=models.CASCADE, null=True,related_name="transportistah")
    transporte = models.ForeignKey(Transporte, on_delete=models.CASCADE, null=True,related_name="transporteh")
    comentariosTransportista = models.TextField(default="",null=True)   

feriavirtualapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from requests import post
from .models import *
from django.contrib import admin
from django.db.models.signals import post_save
from django.dispatch import receiver

class FormRegistroUsuario(UserCreationForm):

    email = forms.EmailField()
    password1 = forms.CharField(label='Contraseña',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirma Contraseña',widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','dni','email','password1','password2','rol','direccion','codigopostal']
        help_texts = {k:"" for k in fields}
class FormRegistroInterno(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contraseña',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirma Contraseña',widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','dni','email','password1','password2','direccion','codigopostal']
        help_texts = {k:"" for k in fields}
        


class FormPujarSubasta(forms.Form):
    cantidad = forms.IntegerField(help_text="Ingrese la cantidad que desea aportar para satisfacer el pedido.")

class FormProductos(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ('producto','variedad','calibre','cantidad','precio', 'imagen',)
        labels = {
            'cantidad': ('Cantidad en cajas:'),
        }
class FormContratos(forms.ModelForm):
    def __init__(self, *args, **kwargs):

        super(FormContratos, self).__init__(*args, **kwargs)
        self.fields['usuario'].queryset = User.objects.filter(rol="1")  | User.objects.filter(rol="1")
    class Meta:
        model = Contrato
        fields = ('usuario','fecha_inicio','fecha_termino')

class FormVenta(forms.ModelForm):
    def __init__(self, *args, **kwargs):

        super(FormVenta, self).__init__(*args, **kwargs)
        self.fields['cliente'].queryset = User.objects.filter(rol="3")  | User.objects.filter(rol="2")
    class Meta:
        model = Post
        fields = ('cliente','producto','variedad','calibre','cantidad_necesaria','refrigeracion','contenido', 'imagen',)
class FormVentaCliente(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('producto','variedad','calibre','cantidad_necesaria','refrigeracion','contenido', 'imagen',)
        labels = {
            'cantidad_necesaria': ('Cantidad en cajas:'),
            'imagen': ('Imagen de referencia (opcional)')
        }
    def __init__(self, *args, **kwargs):
        super(FormVentaCliente, self).__init__(*args, **kwargs)
        self.fields['imagen'].required = False



class FormSolicitudEstadoTransportista(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['EstadoSolicitud'].choices = [
                ("11", "En camino"),
                ("12", "Viaje interrumpido"),
                ("13", "Destino"),
            ]
    class Meta:
        model = Post
        fields = ('EstadoSolicitud',)
class FormSolicitudEstadoRevisor(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['EstadoSolicitud'].choices = [
                ("9", "Rechazar"),
                ("10", "Aprobar"),
            ]
    class Meta:
        model = Post
        fields = ('EstadoSolicitud',)
class FormSolicitudEstadoProductor(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['EstadoSolicitud'].choices = [
                ("6", "Entregado en bodega"),
                ("7", "Viaje Interrumpido")

            ]
    class Meta:
        model = Post
        fields = ('EstadoSolicitud',)    
class FormSolicitudClienteExterno(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['EstadoSolicitud'].choices = [
                ("14", "Pagar"),
                ("15", "Rechazar pedido"),

            ]
    class Meta:
        model = Post
        fields = ('EstadoSolicitud',)    
class FormSolicitudEstado(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['EstadoSolicitud'].choices = [
                ("1", "Aprobado"),
                ("2", "Rechazado"),
                ("3", "Pendiente")
            ]
    class Meta:
        model =  Post
        fields = ('EstadoSolicitud',)



class FormRegistrarTransporte(forms.ModelForm):
    class Meta:
        model = Transporte
        fields = ('tamaño','refrigeracion','tarifa','disponible')

feriavirtualapp/templates/Iniciar-venta.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}

<div class="main">
    
    <form class="form rounded "  style="background-color:#ffffffc1" method="POST" enctype="multipart/form-data">
        <h1>Inicia una venta!.</h1>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" name="register">
    </form>
</div>


{% endblock %}

feriavirtualapp/templates/Solicitud.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}

<div class="main">
    
    <form class="form rounded "  style="background-color:#ffffffc1" method="POST" enctype="multipart/form-data">
        <h1>Inicia una venta</h1>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class=" rounded "  style="background-color:#22d14edb" name="register">
    </form>
</div>


{% endblock %}

feriavirtualapp/templates/contratos.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}

<div class="main">
    
    <form class="form rounded "  style="background-color:#ffffffc1" method="POST" enctype="multipart/form-data">
        <h1>Registrar contrato.</h1>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit"  class=" rounded "  style="background-color:#22d14edb" value="Guardar" name="register">
    </form>
</div>


{% endblock %}

feriavirtualapp/templates/gestion-contratos.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}

<div class="main">

    
    <a href="{% url 'contratos' %}" ><input class="rounded" style="background-color:#8cc080" type="submit" value="Crear nuevo contrato"></input></a>
    <a href="{% url 'listaContratos' %}"><input class="rounded" style="background-color:#8cc080" type="submit" value="Lista de contratos"></input></a>

</div>


{% endblock %}

feriavirtualapp/templates/login.html
{% extends 'baseboostrap.html' %}

{% block content %}
<div class="main">
    
    <form class="form rounded "  style="background-color:#ffffffc1" method="POST">
        <h1>¡Ingresa!</h1>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class=" rounded "  style="background-color:#22d14edb" name="register" value="Ingresar">
        <p class="registro">o también puedes <a href="{% url 'register-interno' %}"><b style="color: #00ba8ffe">registrarte.</b></a></p>
    </form>
    
        
   
</div>
{% endblock %}

feriavirtualapp/templates/logout.html
{% extends 'baseboostrap.html' %}

{% block content %}
<div class="main">
    <p>Te has deslogeado...click <a href="{% url 'login' %}" style="color: #00ff00;">Aquí</a> para volver al inicio</p>
</div>
{% endblock %}  

feriavirtualapp/templates/notificacion.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}
<h1>Solicitudes de pago.</h1>
{% for n in notis %}

<article >
<div class="container-article" style="background-color:#999999" >
    <div class="cont-noti">
        
        <br>

        <h2>Enviado por: {{n.post.user.username}}</h2>
        <h2>Fruta total: {{n.post.cantidad_actual}} Kg</h2>
        {% for parts in n.post.participantes %}
        <h2>Participantes: {{parts.username}}</h2>
        {% endfor %}
        <br>
        <h2>Total: ${{n.total}}</h2>
        <a class="notificar" href="{% url 'pagar' total=n.total pk=n.pk %}">
            <input type="submit" class=" rounded "  style="background-color:#22d14edb"  value="Pagar">
        </a>
  
    </div>
</div>
</article>


{% endfor %}
{% endblock %}

feriavirtualapp/templates/pagar.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}
<article>
    <div class="container-article">
        <h1>Confirmación de pago.</h1>
        
        <h2>Total final: ${{total}}</h2>
        
        <form action="{{ response.url }}" method="POST" class="btn-pagar">{% csrf_token %}
            <input type="hidden" name="token_ws" value="{{response.token}}">
            <input type="hidden" name="username" value="{{request.user.username}}">
            <img class="webpay" src="/media/webpay.png" alt="">
            <input type="submit" value="Ejecutar Pago con Webpay">
        </form>
        <br>
    </div>
</article>
{% endblock %}

feriavirtualapp/templates/registrarTransporte.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}

<div>
    <form method="POST"  class="rounded" style="background-color:#ffffffc1" action="">
        {% csrf_token %}
        {{ form.as_p }}     
        
        <input type="submit" class="btn-mod rounded "  style="background-color:#22d14edb"  value="Registrar">
    </form>
</div>

{% endblock %}

feriavirtualapp/templates/solicitudesClienteExterno.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}

<div class="main">
  <div class="table-responsive" >
    <table class="table table-light table-striped" style="background-color:#ffffffc1;">
      <tr class="table-active">
      
          <!-- <td><b>Usuario </b></td> -->
          <td><b>Producto</b></td>
          <td><b>Variedad</b></td>
          <td><b>Calibre</b></td>
          <td><b>Cantidad_actual</b></td>
          <td><b>Cantidad_necesaria</b></td>
          <td><b>Contenido</b></td>
          <td><b>Cliente</b></td>
          <td><b>Fecha_creacion</b></td>
          <!-- <td><b>Direccion</b></td> -->
          <!-- <td><b>Codigo Postal</b></td> -->
          <td><b>Estado Solicitud Compra</b></td>
          <!-- <td><b>Imagen</b></td> -->
          <td><b>ModEstado</b></td>

        {% for s in soli %} 
        <tr>
      
            <!-- <td>{{ s.usuario.username }}</td> -->
        
            <td>{{ s.get_producto_display }}</td>
    
            <td>{{ s.variedad }}</td>
            
            <td>{{ s.get_calibre_display }}</td>
  
            <td>{{ s.cantidad_actual }}</td>

            <td>{{ s.cantidad_necesaria }}</td>

            <td>{{ s.contenido }}</td>

            <td>{{ s.cliente }}</td>

            <td>{{ s.fecha_creacion|date:"d/m/Y" }}</td>

            <!-- <td>{{ s.usuario.direccion }}</td> -->

            <!-- <td>{{ s.usuario.codigopostal }}</td> -->

            <td>{{ s.get_EstadoSolicitud_display }}</td>
            {% if person.image %}
            <!-- <td> <img style="height: 100px;"  src="{{ s.imagen.url }}"> </td> -->
            {% else %}
            <!-- <td><b></b></td> -->
            {% endif %}
            {% if s.EstadoSolicitud == "13"%}
            <td><p class="boton_mod"><a  href="{% url 'modificarSolicitudClienteExterno' s.pk%}"  style="background-color:#71da8cdb; color: black;">Pagar o rechazar</a></p></td>
            {% endif %}

          
        
          </tr>
        {% endfor %}
      </table>
    </div>


</div>



  


{% endblock %}

feriavirtualapp/templates/solicitudesProductor.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}

<div class="main">
  <div class="table-responsive">
    <table class="table table-light table-striped" style="background-color:#ffffffc1;">
      <tr class="table-active">
      
          <!-- <td><b>Usuario </b></td> -->
          <td><b>Producto</b></td>
          <td><b>Variedad</b></td>
          <td><b>Calibre</b></td>
          <td><b>Cantidad_actual</b></td>
          <td><b>Cantidad_necesaria</b></td>
          <td><b>Contenido</b></td>
          <td><b>Cliente</b></td>
          <td><b>Fecha_creacion</b></td>
          <!-- <td><b>Destino</b></td> -->
          <!-- <td><b>Codigo Postal</b></td> -->
          <td><b>Estado productos</b></td>
          <!-- <td><b>Imagen</b></td> -->
          <td><b>Notificar entrega de productos</b></td>

        {% for s in solip %} 
        <tr>
      
            <!-- <td>{{ s.usuario.username }}</td> -->
        
            <td>{{ s.get_producto_display }}</td>
    
            <td>{{ s.variedad }}</td>
            
            <td>{{ s.get_calibre_display }}</td>
  
            <td>{{ s.cantidad_actual }}</td>

            <td>{{ s.cantidad_necesaria }}</td>

            <td>{{ s.contenido }}</td>

            <td>{{ s.cliente }}</td>

            <td>{{ s.fecha_creacion|date:"d/m/Y" }}</td>

            <!-- <td>{{ s.usuario.direccion }}</td> -->

            <!-- <td>{{ s.usuario.codigopostal }}</td> -->

            <td>{{ s.get_EstadoSolicitud_display }}</td>

            {% if s.imagen %}
            <!-- <td> <img style="height: 100px;"  src="{{ s.imagen.url }}"> </td> -->
            
            {% else %}
            <td><b></b></td>
            {% endif %}
            <td><p class="boton_mod"><a  href="{% url 'modificarsolicitudProductor' s.pk%}"  style="background-color:#71da8cdb; color: black;">Actualizar estado</a></p></td>
          </tr>
        {% endfor %}
      </table>
    </div>


</div>



  


{% endblock %}

feriavirtualapp/templates/subasta.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}
<div class="main">
    <form class="form rounded" method="POST" enctype="multipart/form-data">
        <h1>Participar en la subasta con tus productos.</h1>
        
        <span class="helptext"> Faltan {{resta}} kg de fruta para satisfacer este pedido.</span>
        <br>
        <br>
        {% csrf_token %}
        {{form.as_p}}
        
        <input type="submit" name="register">
    </form>
</div>
{% endblock %}

feriavirtualapp/templates/transportesRegistrados.html
{% extends 'baseboostrap.html' %}
{% load humanize %}
{% block content %}

<div class="main">
  <div class="table-responsive">
    <table class="table table-light table-striped">
      <tr class="table-active">
          <td><b>Tamaño</b></td>
          <td><b>Refrigeracion</b></td>
          <td><b>Tarifa</b></td>
          <td><b>Disponibilidad</b></td>
          <td><b>ModEstado</b></td>

        {% for t in transp %} 
        <tr>
      
            <td>{{ t.get_tamaño_display  }}</td>
        
            <td>   
            {% if t.refrigeracion == True  %}
              Refrigerado
            {% else %}
              No Refrigerado  
            {% endif %}</td>
    
            <td>{{ t.tarifa }}</td>

            <td>
            {% if t.disponible == True  %}
              Disponible
            {% else %}
              No disponible
            {% endif %}
            </td>

            <td><p class="boton_mod rounded "><a href="{% url 'modificarTransporte' t.id %}">Modificar</a></p></td>
          </tr>
        {% endfor %}
      </table>
      <!-- <a href="{% url 'registrarTransporte' %}" class="download" style="color: #000;">Agregar Transporte</a> -->
    </div>


</div>
{% endblock %}